# Generated by Django 4.2.7 on 2025-11-22 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('duration_ms', models.IntegerField()),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('popularity', models.IntegerField(default=0)),
                ('energy', models.FloatField(default=0.0)),
                ('valence', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Spotify Track',
                'verbose_name_plural': 'Spotify Tracks',
            },
        ),
        migrations.CreateModel(
            name='SpotifyPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('total_tracks', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spotify Playlist',
                'verbose_name_plural': 'Spotify Playlists',
                'ordering': ['-created_at'],
            },
        ),
    ]
