# Generated by Django 4.2.7 on 2025-11-22 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('neutral', 'Neutral'), ('surprised', 'Surprised'), ('fear', 'Fear'), ('disgust', 'Disgust')], max_length=20)),
                ('confidence', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='mood_images/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Detection Result',
                'verbose_name_plural': 'Mood Detection Results',
                'ordering': ['-detected_at'],
            },
        ),
    ]
