# Generated by Django 4.2.7 on 2025-12-19 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotify_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyplaylist',
            name='genres_used',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spotifyplaylist',
            name='mood',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='spotifyplaylist',
            name='spotify_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spotify User',
                'verbose_name_plural': 'Spotify Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('neutral', 'Neutral'), ('surprised', 'Surprised'), ('fear', 'Fear'), ('disgust', 'Disgust'), ('excited', 'Excited'), ('confident', 'Confident'), ('motivated', 'Motivated'), ('dancing', 'Dancing'), ('romantic', 'Romantic'), ('peaceful', 'Peaceful'), ('energetic', 'Energetic'), ('melancholic', 'Melancholic'), ('playful', 'Playful')], max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Detection Result',
                'verbose_name_plural': 'Mood Detection Results',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['-detected_at'], name='spotify_int_detecte_6ffdf2_idx'), models.Index(fields=['user', '-detected_at'], name='spotify_int_user_id_95f6eb_idx')],
            },
        ),
    ]
